Repository TheDarkSide1992/UwUgle, pull requests merged in 2025-03, with the labels that each got.

#2 Added Logger and Events
  Packages/Events/Events.csproj
  Packages/Events/Events.sln
  Packages/Events/Ping.cs
  Packages/Logger/Logger.csproj
  Packages/Logger/Logger.sln
  Packages/Logger/LoggerExtension.cs
  Packages/Logger/Monitor.cs
  docker-compose.yml
Labels: enhancement, good first issue

#3 Initial SearchEngine Projects and Solution
  Apps/SearchEngine/API/API.csproj
  Apps/SearchEngine/API/Controllers/SearchEngineController.cs
  Apps/SearchEngine/API/Program.cs
  Apps/SearchEngine/API/Properties/launchSettings.json
  Apps/SearchEngine/API/appsettings.Development.json
  Apps/SearchEngine/API/appsettings.json
  Apps/SearchEngine/Infrastructure/Infrastructure.csproj
  Apps/SearchEngine/Infrastructure/SearchRepository.cs
  Apps/SearchEngine/SearchEngine.sln
  Apps/SearchEngine/Service/SearchService.cs
  Apps/SearchEngine/Service/Service.csproj
Labels: enhancement, good first issue

#4 Initial File cleaner Projects and Solution
  Apps/FileCleaner/ConsoleApplication/ConsoleApplication.csproj
  Apps/FileCleaner/ConsoleApplication/Program.cs
  Apps/FileCleaner/FileCleaner.sln
  Apps/FileCleaner/Service/CleanerService.cs
  Apps/FileCleaner/Service/Service.csproj
Labels: enhancement, good first issue

#5 added initial solution and project structure for micros service
  Apps/FileReader/ConsoleApplication/ConsoleApplication.csproj
  Apps/FileReader/ConsoleApplication/Program.cs
  Apps/FileReader/FileReader.sln
  Apps/FileReader/Infrastructure/Class1.cs
  Apps/FileReader/Infrastructure/Implementations/.gitkeep
  Apps/FileReader/Infrastructure/Infrastructure.csproj
  Apps/FileReader/Infrastructure/Interfaces/IReader.cs
  Apps/FileReader/Service/Class1.cs
  Apps/FileReader/Service/Implementations/.gitkeep
  Apps/FileReader/Service/Interfaces/IService.cs
  Apps/FileReader/Service/Service.csproj
Labels: enhancement, good first issue

#6 Search engine/feature/api
  Apps/SearchEngine/.dockerignore
  Apps/SearchEngine/API/API.csproj
  Apps/SearchEngine/API/Controllers/SearchEngineController.cs
  Apps/SearchEngine/API/Program.cs
  Apps/SearchEngine/Dockerfile
  Apps/SearchEngine/Infrastructure/Implementations/SeartchRepositoryDocument.cs
  Apps/SearchEngine/Infrastructure/Implementations/SeartchRepositoryString.cs
  Apps/SearchEngine/Infrastructure/Infrastructure.csproj
  Apps/SearchEngine/Infrastructure/Interface/ISearchRespository.cs
  Apps/SearchEngine/Infrastructure/SearchRepository.cs
  Apps/SearchEngine/SearchEngine.sln
  Apps/SearchEngine/Service/Implementations/ServiceDocument.cs
  Apps/SearchEngine/Service/Implementations/ServiceString.cs
  Apps/SearchEngine/Service/Interfaces/Iservice.cs
  Apps/SearchEngine/Service/SearchService.cs
  Apps/SearchEngine/Service/Service.csproj
  Packages/SharedModels/Document.cs
  Packages/SharedModels/DocumentSimple.cs
  Packages/SharedModels/SharedModels.csproj
  Packages/SharedModels/SharedModels.sln
  Packages/SharedModels/Word.cs
  docker-compose.yml
Labels: enhancement

#7 updated docker file to include postgress db
  docker-compose.yml
Labels: enhancement

#8 Search engine/feature/sql
  Apps/SearchEngine/API/API.csproj
  Apps/SearchEngine/API/Controllers/SearchEngineController.cs
  Apps/SearchEngine/API/Program.cs
  Apps/SearchEngine/Dockerfile
  Apps/SearchEngine/Infrastructure/Entities/DocumentEntity.cs
  Apps/SearchEngine/Infrastructure/Implementations/Mappers/FileMapper.cs
  Apps/SearchEngine/Infrastructure/Implementations/SeartchRepositoryDocument.cs
  Apps/SearchEngine/Infrastructure/Implementations/SeartchRepositoryString.cs
  Apps/SearchEngine/Infrastructure/Infrastructure.csproj
  Apps/SearchEngine/SearchEngine.sln
  Apps/SearchEngine/Service/Implementations/ServiceDocument.cs
  Apps/SearchEngine/Service/Service.csproj
  Packages/Logger/Monitoring.cs
  SQL/PostgresSQL/Create.sql
  SQL/PostgresSQL/MockData.sql
  docker-compose.yml
Labels: enhancement

#10 set up event to be able to help with connecting to rabbitMq
  Packages/Events/EventModels/BaseEventModel.cs
  Packages/Events/Events.csproj
  Packages/Events/Ping.cs
  Packages/Events/RabbitMqConnectionHelper.cs
Labels: enhancement

#13 Feat/file indexer
  Apps/FileIndexer/.dockerignore
  Apps/FileIndexer/ConsoleApplication/ConsoleApplication.csproj
  Apps/FileIndexer/ConsoleApplication/Program.cs
  Apps/FileIndexer/Dockerfile
  Apps/FileIndexer/FileIndexer.sln
  Apps/FileIndexer/Infrastructure/IndexRepository.cs
  Apps/FileIndexer/Infrastructure/Infrastructure.csproj
  Apps/FileIndexer/Infrastructure/Interfaces/IIndexRepository.cs
  Apps/FileIndexer/Infrastructure/Repositories/PgIndexRepository.cs
  Apps/FileIndexer/Service/Helpers/DatabaseConnectionHelper/DbConnectionHelper.cs
  Apps/FileIndexer/Service/Helpers/Indexers/WordIndexerHelper.cs
  Apps/FileIndexer/Service/Helpers/Interfaces/IIndexer.cs
  Apps/FileIndexer/Service/IndexService.cs
  Apps/FileIndexer/Service/Service.csproj
  Packages/Events/Events.sln
  Packages/Logger/Logger.sln
  Packages/Logger/Monitoring.cs
  Packages/SharedModels/Document.cs
  Packages/SharedModels/SharedModels.sln
  docker-compose.yml
Labels: enhancement

#15 Frontend/feature/set up
  Apps/FileCleaner/ConsoleApplication/Program.cs
  Apps/FileCleaner/Service/CleanerService.cs
  Apps/FileCleaner/Service/Implementations/Cleaners/CleanerStringSpacing.cs
  Apps/SearchEngine/API/Program.cs
  Apps/SearchEngine/Infrastructure/Implementations/SeartchRepositoryDocument.cs
  Frontend/.dockerignore
  Frontend/.editorconfig
  Frontend/.gitignore
  Frontend/.gitkeep
  Frontend/Dockerfile
  Frontend/README.md
  Frontend/angular.json
  Frontend/nginx.conf
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/public/favicon.ico
  Frontend/public/favicon.old.ico
  Frontend/src/app/Envirements/envirement.ts
  Frontend/src/app/app.component.html
  Frontend/src/app/app.component.scss
  Frontend/src/app/app.component.spec.ts
  Frontend/src/app/app.component.ts
  Frontend/src/app/app.config.ts
  Frontend/src/app/app.routes.ts
  Frontend/src/app/models/DocumentSimple.model.ts
  Frontend/src/index.html
  Frontend/src/main.ts
  Frontend/src/styles.css
  Frontend/tsconfig.app.json
  Frontend/tsconfig.json
  Frontend/tsconfig.spec.json
  docker-compose.yml
  scripts/sql-set-up.sh
Labels: enhancement

#16 Update README.md with favicon.ico icon
  README.md
Labels: enhancement

#17 File reader/feature/reader
  Apps/FileReader/.dockerignore
  Apps/FileReader/ConsoleApplication/ConsoleApplication.csproj
  Apps/FileReader/ConsoleApplication/Program.cs
  Apps/FileReader/Dockerfile
  Apps/FileReader/FileReader.sln
  Apps/FileReader/Infrastructure/Class1.cs
  Apps/FileReader/Infrastructure/Implementations/Reader.cs
  Apps/FileReader/Infrastructure/Infrastructure.csproj
  Apps/FileReader/Infrastructure/Interfaces/IReader.cs
  Apps/FileReader/Infrastructure/Models/FilesModel.cs
  Apps/FileReader/Infrastructure/maildir/.gitkeep
  Apps/FileReader/Service/Class1.cs
  Apps/FileReader/Service/Implementations/ReaderService.cs
  Apps/FileReader/Service/Interfaces/IService.cs
  Apps/FileReader/Service/Service.csproj
  docker-compose.yml
Labels: enhancement

#18 fixed docker file issue for filereader
  Apps/FileReader/Dockerfile
  Apps/FileReader/Service/Implementations/ReaderService.cs
  docker-compose.yml
Labels: bug

#20 fixed potential isse for path to script
  scripts/sql-set-up.sh
Labels: bug

#21 patch for script path path might change depending on context
  Apps/SearchEngine/Infrastructure/Implementations/SeartchRepositoryDocument.cs
  docker-compose.yml
  scripts/sql-set-up.sh
Labels: bug

#22 increased max file connections for db
  docker-compose.yml
Labels: bug

#23 set up rabbitmq cluster using rabbitmq and haproxy
  Config/Haproxy.cfg
  Config/rabbitmq.conf
  docker-compose.yml
  scripts/rabbitmq-cluster-setup.sh
Labels: enhancement

#24 Docker/feat/envirement
  README.md
  docker-compose.yml
Labels: enhancement

#25 Search engine/feature/filedownload
  .gitignore
  Apps/SearchEngine/API/Controllers/SearchEngineController.cs
  Frontend/package-lock.json
  Frontend/src/app/app.component.html
  Frontend/src/app/app.component.ts
  Packages/Logger/Monitoring.cs
  SQL/PostgresSQL/Create.sql
  docker-compose.yml
  maildir/.gitkeep
  scripts/sql-set-up.sh
Labels: bug, enhancement

#27 Update README.md
  README.md
Labels: enhancement

#28 Update README.md
  README.md
Labels: enhancement
